### ISSUE TITLE
library can generate I2C frequencies that exceed the slave device capability on fast 32-bit processors

### ISSUE THREAD

**Issue by bxparks** [Seeed-Studio/Arduino_Software_I2C#4]
The `SoftwareI2C::sendByte()` method does not contain a timing delay in the for-loop (e.g. a `delayMicroseconds()`). On very fast 32-bit processors, the `digitalWrite()` is so fast that the effective I2C frequency can exceed the capabilities of the slave device, causing the I2C data transmission to fail. The problem does not happen on slower 32-bit processors and 8-bit AVR processors.

I have observed the problem on 2 processors:

* ESP32: 1300 KHz observed
* Teensy 3.2: 680 kHz observed

I believe many I2C devices have a limit of about 400 kHz, although some of them may work at higher frequencies. Things do seem to get unreliable at the 680 kHz or 1300 kHz generated by this library.

**Comment by Pillar1989** [comment]
https://www.cypress.com/file/396646/download 
![image](https://user-images.githubusercontent.com/4081906/130539164-d54f785a-7261-4582-b417-0d87153e942e.png)
I2C speed reach to 1000kpbs is ok. @bxparks
