### ISSUE TITLE
I2C Clock Speed

### ISSUE THREAD

**Issue by eddie3ruff** [Seeed-Studio/Arduino_Software_I2C#6]
Hi, I have the Seeeduino XAIO. How can I change the I2C clock speed (for example between 100kHz and 400kHz)?

**Comment by Lesords** [comment]
Hello,
I'm sorry it took me so long to reply to you.
Currently this library does not support modifying the clock speed

**Comment by Lesords** [comment]
Hello,

I\'m going to close this issue, feel free to re-open it if you have any other questions.

[Autocommentary]
